# Generated by Django 5.1.1 on 2024-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, verbose_name='Name')),
                ('user_surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Gender')),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
